sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t m3tr0x/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true m3tr0x/docker-react npm run test

